image: registry.gitlab.com/pages/hugo/hugo_extended:latest

before_script:
  - apk update && apk add npm git
  - npm install -g postcss-cli
  - npm install autoprefixer

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
