image: registry.gitlab.com/pages/hugo/hugo_extended:latest

before_script:
  - npm install -g postcss-cli

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
